### ISSUE TITLE
Match style to The Garage

### ISSUE THREAD

**Issue by awmuncy** [tablelandnetwork/admin-ui#16]

**Comment by sanderpick** [comment]
Some live nits on the current layout:
- On landing page, centered connect button can be bigger and match style from garage.
- On landing page, use header color from garage landing page.
- Use logo layout from garage (no "Tableland" text in logo). Steal font for word "Dashboard" like it's used in the garage. 
- Migrate from "dashboard" to "console".
- Make sure we're using the same monospace font as in the garage (andale mono).
- Change footer to match garage (remove version, add icon links to twitter, discord, doc). Should be dark color and shorter.
- Drop the "..." menu
- Alter left menu icon to be circles (details sent in DM)
- Make inactive tabs go more transparent. Remove "active" border. 
- Little plus icons should not change on hover. Make 0.9 opacity (or something) when "active". 
- Remove "grey" buttons. Use opacity to indicate "disabled".
- "Results" box shouldn't change when you start typing (or just hide box until results load)
- Use garage table design for results (no border, no greys, header font should be smaller than results)
- When closing tab, the tab directly to it's left should become active.
- Hide "save" for now
- Query button should have an active style
- Reduce size + increase margin on "Create Table on Ethereum..." text
- Create table column types should not be grey (could use green)
- Create table column types need some extra padding, need to be aligned with header columns
- Commit pending box shouldn't have grey borders, needs more padding, background should be medium green
- Cancel create table should take you back to the table creation w/ values prefilled as they were before
- "Tables on Ethereum" should just say "Your tables"
- Double-click to edit tab name
- Explore making table creation modal-based. Then can add a "create table" button in header.
- After table creation, create modal should close and new table should show up in your list of tables
- My tables should auto-load when refresh page
- Table types under my tables: Remove grey styling. Remove headers, remove lines between types
- Tally box should only pop by clicking an icon in footer
- Feature for later: show all your tables across networks in "my tables"
- Background placeholder text in query text box can be some shade of green

**Comment by sanderpick** [comment]
@awmuncy worth making issues out of these points? we spanned a lot further than "match style to garage". cc @eightysteele for reference

**Comment by awmuncy** [comment]
@sanderpick For some I think I can just tick them, for others I think it's work making tickets. I've updated your comment to include check boxes. To mark them complete, I'll either A) Complete them or B) Create a ticket. For those for which I've created tickets, I'll add links below.

**Comment by eightysteele** [comment]
👀

**Comment by awmuncy** [comment]
I don't love the way the pink color looks in the header on the splash page. I think we should have previewed it before adding this as a to-do. It's an easy change, but I don't love it, so let's revisit it.

**Comment by sanderpick** [comment]
let me know when you've pushed that change and I can take a look, but let's just go with it for now. after thinking about it more, i think we should remove the art from the background and just use a solid color / gradient (trying to not use the art on technical things / docs). i can play around with something in figma.

maybe we can show a couple queries and their results. could be chosen at random from a few different ones on page load. or... something else / CTA that can liven the page up.

**Comment by awmuncy** [comment]
I've pushed the updates, including header color and a gradient background. It's not ideal. If you want to mock-up what you want it to look like, I can match what you're thinking.

**Comment by eightysteele** [comment]
thought: since we're migrating from "dashboard" to "console", wondering if we want to additionally change the url subdomain from "dash" to "console".

**Comment by awmuncy** [comment]
I've updated the ingress so that console.tableland.xyz will point to the app. We'll need to update the DNS @sanderpick

**Comment by sanderpick** [comment]
cool. i can take a look in a bit. have to run to meeting now.

**Comment by sanderpick** [comment]
@awmuncy looking at latest since I see you checked off a bunch of things. On the landing page, this still isn't looking like the garage style. See https://garage.dev.tableland.xyz.
- The buttons don't match
- The logo doesn't match (not same spacing)

<img width="2560" alt="Screen Shot 2022-11-10 at 11 48 09 AM" src="https://user-images.githubusercontent.com/361000/201192122-1f2d80a8-560a-4aba-a895-5108216659e1.png">

**Comment by sanderpick** [comment]
k, added the DNS entries to import domain to app engine.

**Comment by awmuncy** [comment]
The Splash page should look better now. I had to change the button and logo text temporarily, and add some copy. (See Andrew's chats in contributor chat). The button and logo text I'll revert in a few days back to simply "Console" and "Connect Wallet"

**Comment by sanderpick** [comment]
awesome. looks good! (minimal, but good... we can spruce it up later)

**Comment by eightysteele** [comment]
niiiiice. small nit—could we "minimize" the feedback modal somehow? it's pretty violent on the eyes, sucking me in haha

**Comment by awmuncy** [comment]
@eightysteele Yep! Just pushed an update that does that a few seconds ago.

**Comment by awmuncy** [comment]
@sanderpick I updated the styles a little bit to make the tabs pane and the icon menu on the left to have a margin. I think it's a little more consistent with the garage, but you can tell me if it doesn't sit right.

**Comment by eightysteele** [comment]
@awmuncy reading my 🧠

**Comment by awmuncy** [comment]
@sanderpick Any more notes on this? I've finished all the items, or created tickets for them.

**Comment by eightysteele** [comment]
@awmuncy how do you think it's looking? any nits from your side? :)

**Comment by awmuncy** [comment]
For this ticket, I like where it's at. (This ticket being "Match style to The Garage") though it can be a bit subjective. Got several other things that don't fit in this ticket per se.

**Comment by eightysteele** [comment]
awesome. when you have a sec, i would love to lurk on the list of other things that you're cooking up (and of course help with any dog fooding, etc.). :)

**Comment by awmuncy** [comment]
@eightysteele  For relative near term updates, the [Dashboard Debut](https://github.com/orgs/tablelandnetwork/projects/28) project has a lot of the tickets I'm working on. There's also the [Dashboard Backlog](https://github.com/orgs/tablelandnetwork/projects/11) project. Pretty much any ticket on the admin-ui repository. If you've got ideas, sling them my way.
